import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'com.github.johnrengelman.shadow' version '8.1.1'

	alias libs.plugins.curseForgeGradle apply(true)
	alias libs.plugins.modrinthMinotaur apply(true)
}

version = project.mod_version
group = project.maven_group

def modVersion = project.mod_version.toString()
def modVersionWithoutSuffix = modVersion.contains("_") ? modVersion.substring(0, modVersion.indexOf("_")) : modVersion

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		url "https://maven.terraformersmc.com/releases/"
	}
	maven {
		url "https://maven.twelveiterations.com/repository/maven-public/"

		content {
			includeGroup "net.blay09.mods"
		}
	}
	mavenCentral()
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"speedrunnermod" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	accessWidenerPath = file("src/main/resources/speedrunnermod.accessWidener")
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Kuma Keybind API
	implementation "net.blay09.mods:kuma-api-common:$kuma_version"
	include "net.blay09.mods:kuma-api-fabric:$kuma_version"

	// Fabric API
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Mod Menu
	implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

	// Reflections (no longer required)
	// implementation "org.reflections:reflections:${project.reflections_verison}"
	// include "org.reflections:reflections:${project.reflections_verison}"

	// Java Assist (no longer required)
	// implementation "org.javassist:javassist:${project.javassist_version}"
	// include "org.javassist:javassist:${project.javassist_version}"
}

shadowJar {
	// No longer required
	// relocate 'org.reflections', 'net.dillon.shadowed.reflections'
	// relocate 'javassist', 'net.dillon.shadowed.javassist'
}

processResources {
	inputs.property "mod_version", modVersionWithoutSuffix
	inputs.property "mc_version", project.mc_version

	filesMatching("fabric.mod.json") {
		expand "mod_version": modVersionWithoutSuffix,
				"mc_version": project.mc_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

tasks.register('curseforge', TaskPublishCurseForge) {
	dependsOn('build')
	description = 'Publishes the Fabric build to CurseForge.'
	group = 'publishing'

	apiToken = project.findProperty("curseforge.api_key") ?: System.getenv("CURSEFORGE_TOKEN") ?: "none"

	def projectId = findProperty("curseforge_project_id")
	onlyIf {
		projectId != null
	}
	if (projectId) {
		def mainFile = upload(findProperty("curseforge_project_id"), tasks.named("jar", Jar).get().archiveFile.get().asFile)
		mainFile.displayName = "[${mc_version.substring(2)}] $mod_name ${modVersionWithoutSuffix}"
		mainFile.changelog = rootProject.file("${changelog_file}").text
		mainFile.addRequirement("fabric-api")
		def supportedVersions = supported_mc_versions
				.split(",")
				.collect { it.trim() }
		supportedVersions.each { v ->
			mainFile.addGameVersion(v)
		}
		mainFile.releaseType = "release"
		project.findProperty("curseforge_environments")?.split(",")?.toList()?.each { mainFile.addEnvironment(it) }
	}
}

modrinth {
	token = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN") ?: "none"
	projectId = findProperty("modrinth_project_id")

	versionNumber = modVersionWithoutSuffix
	versionName = "[mc${minecraft_version}] ${mod_name} ${modVersionWithoutSuffix}"

	uploadFile = tasks.named("jar")
	def changelogFile = rootProject.file("${changelog_file}")
	if (changelogFile.exists()) {
		changelog = changelogFile.text
	}
	def supportedVersions = supported_mc_versions
			.split(",")
			.collect { it.trim() }
	gameVersions = supportedVersions
	loaders = ['fabric']
	dependencies {
		required.project "fabric-api"
	}
}