import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
	id 'maven-publish'

	alias libs.plugins.fabricLoom
	alias libs.plugins.curseForgeGradle apply(true)
	alias libs.plugins.modrinthMinotaur apply(true)
}

version = project.mod_version
group = project.maven_group

def modVersion = project.mod_version.toString()
def modVersionWithoutSuffix = modVersion.contains("_") ? modVersion.substring(0, modVersion.indexOf("_")) : modVersion

loom {
	splitEnvironmentSourceSets()

	mods {
		"speedrunnermod" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	def aw = file("src/main/resources/${mod_id}.accessWidener")
	if (aw.exists()) {
		accessWidenerPath.set(aw)
	}
	mixin {
		defaultRefmapName.set("${mod_id}.refmap.json")
	}

	runs {
		client {
			client()
			setConfigName('Minecraft Client')
			ideConfigGenerated(true)

			jvmArguments.add("-Ddevauth.enabled=" + "${devauth_enabled}")
		}
		server {
			server()
			setConfigName('Minecraft Server')
			ideConfigGenerated(true)
		}
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'
apply from: 'resources.gradle'

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

tasks.register('curseforge', TaskPublishCurseForge) {
	dependsOn('build')
	description = 'Publishes the Fabric build to CurseForge.'
	group = 'publishing'

	apiToken = project.findProperty("curseforge.api_key") ?: System.getenv("CURSEFORGE_TOKEN") ?: "none"

	def projectId = findProperty("curseforge_project_id")
	onlyIf {
		projectId != null
	}
	if (projectId) {
		def mainFile = upload(findProperty("curseforge_project_id"), tasks.named("jar", Jar).get().archiveFile.get().asFile)
		mainFile.displayName = "[${mc_version.substring(2)}] $mod_name ${modVersionWithoutSuffix}"
		mainFile.changelog = rootProject.file("${changelog_file}").text
		mainFile.addRequirement("fabric-api")
		mainFile.addRequirement("dillonlib")
		def supportedVersions = supported_mc_versions
				.split(",")
				.collect { it.trim() }
		supportedVersions.each { v ->
			mainFile.addGameVersion(v)
		}
		mainFile.releaseType = "release"
		project.findProperty("curseforge_environments")?.split(",")?.toList()?.each { mainFile.addEnvironment(it) }
		mainFile.addEnvironment("Client")
		mainFile.addEnvironment("Server")
	}
}

modrinth {
	token = project.findProperty("modrinth.token") ?: System.getenv("MODRINTH_TOKEN") ?: "none"
	projectId = findProperty("modrinth_project_id")

	versionNumber = modVersionWithoutSuffix
	versionName = "[mc${minecraft_version}] ${mod_name} ${modVersionWithoutSuffix}"

	uploadFile = tasks.named("jar")
	def changelogFile = rootProject.file("${changelog_file}")
	if (changelogFile.exists()) {
		changelog = changelogFile.text
	}
	def supportedVersions = supported_mc_versions
			.split(",")
			.collect { it.trim() }
	gameVersions = supportedVersions
	loaders = ['fabric']
	dependencies {
		required.project "fabric-api"
		required.project "dillon-lib"
	}
}