dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Kuma Keybind API
    implementation "net.blay09.mods:kuma-api-common:$kuma_version"
    include "net.blay09.mods:kuma-api-fabric:$kuma_version"

    // Fabric API
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Mod Menu
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    // DillonLib.
    implementation "maven.modrinth:dillon-lib:${project.dillonlib_dependency}"

    // Reflections (no longer required)
    // implementation "org.reflections:reflections:${project.reflections_verison}"
    // include "org.reflections:reflections:${project.reflections_verison}"

    // Java Assist (no longer required)
    // implementation "org.javassist:javassist:${project.javassist_version}"
    // include "org.javassist:javassist:${project.javassist_version}"
}