dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "maven.modrinth:dillon-lib:${project.mc_version}-${project.dillonlib_version}-fabric"
    implementation "net.blay09.mods:kuma-api-common:$kuma_version"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "net.litetex.mcm:dev-auth-neo:${project.devauth_neo_version}"

    include "net.blay09.mods:kuma-api-fabric:$kuma_version"
}