dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation("net.blay09.mods:balm-fabric:${balm_version}") {
        changing = balm_version.contains('SNAPSHOT')
    }

    implementation "net.dillon.dillonlib:dillonlib-fabric-mc26.3:unspecified"
    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "net.litetex.mcm:dev-auth-neo:${project.devauth_neo_version}"

    runtimeOnly "net.dillon.qualityofqueso:qualityofqueso-fabric-mc26.3:unspecified"
    runtimeOnly "net.dillon.simplekeybinds:simplekeybinds-fabric-mc26.3:unspecified"
}