org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=26.1.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

mod_version=1.12.1_fabric+mc26.1
maven_group=net.dillon.speedrunnermod
archives_base_name=speedrunnermod

fabric_version=0.145.4+26.1.1

modmenu_version=18.0.0-alpha.6

reflections_verison=0.10.2
javassist_version= 3.29.2-GA