# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
minecraft_version = 1.21.8
yarn_mappings = 1.21.8+build.1
loader_version = 0.16.14

# Mod Properties
mod_version = 1.11.3-fabric+mc1.21.6x
maven_group = net.dillon.speedrunnermod
archives_base_name = speedrunner-mod

# Dependencies
fabric_version = 0.129.0+1.21.8

# APIs
modmenu_version = 15.0.0-beta.3
reflections_verison = 0.10.2
javassist_version = 3.29.2-GA