# Common
java_version=25
minecraft_version=26.3
devauth_enabled=1
# Use "-alpha.# for snapshots, "-pre.# for pre-releases, "-rc.#" for release candidates
minecraft_version_range=>=26.3 <26.4
mc_version=mc26.3
supported_mc_versions=26.3

# Mod Properties
mod_name=The Speedrunner Mod
mod_version=1.13
mod_id=speedrunnermod
maven_group=net.dillon.speedrunnermod

# Dependencies
# https://modrinth.com/mod/dillon-lib/versions
dillonlib_version=1.1
# https://modrinth.com/mod/modmenu/versions
modmenu_version=21.0.0-beta.1
# https://modrinth.com/mod/yacl/versions , https://maven.isxander.dev/web/releases/dev/isxander/yet-another-config-lib/
yacl_version=3.9.6+26.3
# https://modrinth.com/mod/dev-auth-neo/versions
devauth_neo_version=1.2.0
# https://modrinth.com/mod/balm , https://maven.twelveiterations.com/service/rest/repository/browse/maven-public/net/blay09/mods/balm-common/
kuma_version=26.3.0.1-SNAPSHOT

# https://fabricmc.net/develop
fabric_api_version=0.160.5+26.3
fabric_loader_version=0.19.5

# Other
curseforge_project_id=452359
modrinth_project_id=blx7Th9B
changelog_file=current_changelog.md

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false